# Site settings
title: Truth. Searching...
email: abatutin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi there! This is my blog about things which get me worried, excited, and just curious.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abatutin.net.blog.s3-website-eu-west-1.amazonaws.com.s3-website-us-east-1.amazonaws.com/" # the base hostname & protocol for your site
twitter_username: DOCTARMD
github_username:  andrewBatutin

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 's3_website.yml']

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
